#define             VAR                 1
#define             CONST               2
#define             IF                  3
#define             ELSE                4
#define             WHILE               5
#define             PRINT               6
#define             READ                7
#define             ID                  8
#define             INTLITERAL          9
#define             CADENA              10
#define             LPAREN              11
#define             RPAREN              12
#define             SEMICOLON           13
#define             COMMA               14
#define             ASSIGNOP            15
#define             PLUSOP              16
#define             MINUSOP             17
#define             LBRACE              18
#define             RBRACE              19
#define             PRODOP              20
#define             DIVOP               21
